-- Offense Template (informational only)
-- ========================================================
-- Purpose:
--   This script is a documentation template for structured offense modules.
--   Aliases should only toggle/arm the route. The real logic should live in a
--   dedicated route script/module.
--
-- Recommended public surface for every offense route:
--   init()
--   reset(reason)
--   enable()
--   disable(reason)
--   is_enabled()
--   is_active()
--   can_run(ctx)
--   build_payload(ctx)
--   on_sent(payload, ctx)
--   status()
--
-- Template sections:
-- ========================================================
-- 1) Script toggling / route init-reset
--    - init(), reset(), enable(), disable(), toggle aliases only
--
-- 2) Defensive scripts
--    - route-local defensive helpers if the route owns any
--
-- 3) Anti-defensive scripts
--    - shieldbreak / anti-tumble / anti-fly / anti-rebound helpers
--
-- 4) Instant kill scripts
--    - reserved burst / execute windows only
--
-- 5) Offense automation sequences
--    - build_payload(ctx) / next_action(ctx)
--    - route planning only; do not send directly from here unless legacy
--      fallback support is explicitly required
--
-- 6) Conditional checks
--    - can_run(ctx), target validity, lane readiness, pause/manual suppression,
--      route mode checks
--
-- 7) Miscellaneous scripts that support the offense
--    - aff tracking adapters, timers, local state helpers, debug helpers
--
-- 8) Script toggles and script enders
--    - start(), stop(), status(), commit/on_sent hooks
--
-- Minimal example shape:
-- --------------------------------------------------------
-- Route = Route or {}
-- Route.name = "route_name"
-- Route.cfg = Route.cfg or { enabled = false }
-- Route.state = Route.state or {}
--
-- function Route.init()
--   Route.state = Route.state or {}
-- end
--
-- function Route.reset(reason)
--   Route.state.last_reason = reason or "manual"
-- end
--
-- function Route.enable()
--   Route.cfg.enabled = true
-- end
--
-- function Route.disable(reason)
--   Route.cfg.enabled = false
--   Route.state.last_disable_reason = reason or "manual"
-- end
--
-- function Route.is_enabled()
--   return Route.cfg.enabled == true
-- end
--
-- function Route.is_active()
--   return false -- route-loop ownership decides this
-- end
--
-- function Route.can_run(ctx)
--   if not Route.is_enabled() then return false, "disabled" end
--   if not Route.is_active() then return false, "inactive" end
--   if not ctx or not ctx.target or ctx.target == "" then return false, "no_target" end
--   return true
-- end
--
-- function Route.build_payload(ctx)
--   local ok, why = Route.can_run(ctx)
--   if not ok then return nil, why end
--   return {
--     route = Route.name,
--     target = ctx.target,
--     lanes = { eq = nil, bal = nil, entity = nil },
--     meta = { phase = "open", reason = "example" },
--   }
-- end
--
-- function Route.on_sent(payload, ctx)
-- end
--
-- function Route.status()
--   return { enabled = Route.is_enabled(), active = Route.is_active() }
-- end
-- ========================================================
